### ISSUE TITLE
Unable to build Canopy in Macos

### ISSUE THREAD

**Issue by gjaldon** [Engil/Canopy#85]
Since I couldn't build Canopy on my Archlinux, I tried it on my Macos. Unfortunately, it doesn't build on it too. After upgrading Mirage to 3.0, I ran the ff commands:

```bash
$ opam pin add tyxml --dev
$ mirage configure
$ make depend
$ make
```

Running `make` gives me the ff error:

```bash
File "static1.mli", line 5, characters 8-16:
Error: Unbound module V1
Command exited with code 2.
run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'
     'predicate(mirage_unix),warn(A-4-41-42-44),debug,bin_annot,strict_sequence,principal,safe_string,thread,color(always)'
     '-pkgs'
     'cohttp,conduit,conduit.mirage,decompress,functoria-runtime,io-page,io-page.unix,irmin,irmin-mirage,logs,lwt,magic-mime,mirage-clock,mirage-clock-unix,mirage-flow,mirage-flow-lwt,mirage-http,mirage-kv-lwt,mirage-logs,mirage-runtime,mirage-types,mirage-types-lwt,mirage-unix,nocrypto,nocrypto.lwt,omd,ptime,re,syndic,tcpip,tcpip.stack-socket,tcpip.tcpv4-socket,tcpip.udpv4-socket,tls,tls.mirage,tyxml,uuidm'
     '-cflags' '-g' '-lflags' '-g' '-tag-line' '<static*.*>: warn(-32-34)'
     '-X' '_build-ukvm' 'main.native']: exited with 10
make: *** [build] Error 1
```

Is this a bug or was I supposed to do some additional config?

**Comment by hannesm** [comment]
can you `mirage clean` (or remove `static*ml*` manually).  `V1` in there is a relict of earlier `crunch` days... which `opam info crunch` do you have?  I suspect there may be a conflict missing between `crunch<2` and `mirage3` //cc @yomimono

**Comment by hannesm** [comment]
I added some lower bounds in the mirage tool https://github.com/mirage/mirage/pull/816 (this won't help us with people using mirage-3.0.0 or 3.0.1 or 3.0.2, though -- but will need a release and upgrade cycle)
